### PR TITLE
DeviceSettings: Update Simplified Chinese

### PR DESCRIPTION
**Pull request by JohnsonRan**

### CODE REVIEW

**Review by ALKALiKong233 — APPROVED** [review]
👍

**Review by idoybh — APPROVED** [review]
LGTM

**Comment by idoybh** [comment]
This PR does not allow changes from maintainers so I can't rebase and force push it. Please allow changes from maintainers or rebase it yourself.

**Comment by idoybh** [comment]
Pushed the changes w/o merging the PR to make our life easier :)

**Comment by idoybh** [comment]
thank you @JohnsonRan and @ALKALiKong233

**Pull request closed without merging**
