### PR TITLE
[bluetooth, libinit] Fix device name & various improvements

### PR DESCRIPTION
**Pull request by ghost**
### Changes
* Seems like the "_hack_" used with `BTM_DEF_LOCAL_NAME` stopped working with Android 13. Instead, switch to the newly introduced property `bluetooth.device.default_name`.
* Also, since `18827` & `18825` have the same models, use respectively the same case switch.
* Imrpove indentation (this was a pain to look at while using VSCode)

### CODE REVIEW

**Comment by idoybh** [comment]
I have a few more indentation fixes. Will force-push soon. There's a mix of tabs and spaces going on

**Comment by idoybh** [comment]
Also @RealJohnGalt please review and confirm we won't have to re-pair anything

**Review by idoybh — APPROVED** [review]
lgtm now
[diff](https://github.com/yaap/device_oneplus_sm8150-common/compare/4039d2540a4eacbc06c5cf7bfcc32227dd66265e..d149382dd71bfd4629f4f52e1bb1970138cf71ac) in my force-push

**Comment by ghost** [comment]
Oh, my bad, didn't notice many of those indentations and tabulations. Thank you for the review.

**Comment by poad42** [comment]
There is no point in shipping custom bdroid header is name is now set in
init, that's the entire purpose of this file.

**Comment by ghost** [comment]
That's needed for AOSP Bluetooth, isn't it? If you think it'd work nonetheless, I'll try to delete when I'm home, even though I'd appreciate if that is done separately by someone else.

**Comment by poad42** [comment]
No,
This overrides the default bdroid header to set bt device name. Something like 
https://github.com/yaap/device_xiaomi_lisa/commit/7fbbb6b1c0dbd8af3cefdec485a215e3f1ead907

Should be done.

**Comment by ghost** [comment]
I guess that should be done separately. Thanks.

**Comment by gotenksIN** [comment]
Custom bdroid header is no longer needed with aosp bt
Can just make a seperate commit to remove in same PR

**Comment by ghost** [comment]
meh

**Comment by ghost** [comment]
My bad, this (more like, these) force-pushes include the commit for dropping `bdroid_buildcfg.h` and a properly authored `6f9853a4e51486b6769eea1a5e2c5e8c8829bd8f`. Should be ready to be merged.

**Comment by idoybh** [comment]
Okay. Seems this does work fine for me. Does not require re-pairing anything (mac is the same, after all). Merging. Thank you @0x4nt

**Pull request merged**
