### PR TITLE
[compatibility] Move to `PRODUCT_VENDOR_PROPERTIES`

### PR DESCRIPTION
**Pull request by ghost**
As stated by [Google themselves](https://android.googlesource.com/platform/build/+/HEAD/Changes.md#product-variables), `PRODUCT_DEFAULT_PROPERTY_OVERRIDES` is soon or never going to get deprecated and discouraged. Let's instead use `PRODUCT_VENDOR_PROPERTIES`, which is what they prefer.

### CODE REVIEW

**Comment by poad42** [comment]
did you verify if the behavior is the same?

**Comment by ghost** [comment]
> did you verify if the behavior is the same?

Did not currently verify, but I just applied whatever Google said that's preferred, and the header also specifics _For vendor partition_. But I am kinda confident that it does the same since `PRODUCT_DEFAULT_PROPERTY_OVERRIDES` is named there.

And, just to be sure, Google is also using this for replacing some vendor properties as seen in [some of their Makefiles](https://github.com/yaap/build_make/search?q=PRODUCT_VENDOR_PROPERTIES). Here's the commit where they [also dropped the flag](https://github.com/yaap/build_make/commit/eb49b34b1ea81259e78e1e50d16f087e16a25837).

**Comment by poad42** [comment]
do that, you have to before doing a PR.

**Comment by ghost** [comment]
> do that, you have to before doing a PR.

Sure :)

**Comment by ghost** [comment]
> do that, you have to before doing a PR.

Also, do you mean checking as in making sure `PRODUCT_VENDOR_PROPERTIES` is found by the build system, or checking if it sets the property to `vendor.prop`?

**Comment by poad42** [comment]
It should technically be overriden, so vendor.prop should have these values, as precedence is odm > vendor> product> system

**Pull request closed without merging**
